import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const stolzl = localFont({
	src: "../fonts/stolzl_book.otf",
	variable: "--font-stolzl",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${stolzl.variable} antialiased bg-black min-h-screen text-white`}>
				{children}
			</body>
		</html>
	);
}
